---
title: "NYC COVID-19 Data: Analysis and Visualization"
output: html_notebook
---

# Part 4: Combining Data and Map-Based Visualization

Now, let's get some more information by zip code and save it in a CSV file that we can use.  
```{r}
# myVars <- paste0("B01001_0",sprintf("%02d", 1:49), "E")
# labs <- group_B01001 %>% filter(name %in% myVars) %>% arrange(name) %>% select(name,label)

zcta_data <- getCensus(name = "acs/acs5",
                       vintage = 2018,
                       vars = c("NAME", "B19013_001E", "B01003_001E", "B02001_001E", "B02001_002E",
                                "B01001_002E", "B01001_026E", "B01002_001E", "B01002_002E",
                                "B01002_003E", "B20017_002E", "B20017_005E"),
                       region = paste0("zip code tabulation area:",nyc_zipcode_string),
                       key=myKey)

#update column names
names(zcta_data)[which(names(zcta_data)=="B19013_001E")] <- "Med_Income"
names(zcta_data)[which(names(zcta_data)=="B01003_001E")] <- "Population"
names(zcta_data)[which(names(zcta_data)=="B02001_001E")] <- "Race_Total"
names(zcta_data)[which(names(zcta_data)=="B02001_002E")] <- "White_Total"
names(zcta_data)[which(names(zcta_data)=="B01001_002E")] <- "Male_Total"
names(zcta_data)[which(names(zcta_data)=="B01001_026E")] <- "Fem_Total"
names(zcta_data)[which(names(zcta_data)=="B01002_001E")] <- "Median_Age"
names(zcta_data)[which(names(zcta_data)=="B01002_002E")] <- "Median_Age_Male"
names(zcta_data)[which(names(zcta_data)=="B01002_003E")] <- "Median_Age_Fem"
names(zcta_data)[which(names(zcta_data)=="B20017_002E")] <- "Median_Income_Male"
names(zcta_data)[which(names(zcta_data)=="B20017_005E")] <- "Median_Income_Fem"
```

```{r}
bor_data <- getCensus(name = "acs/acs5",
vintage = 2018,
vars = c("NAME", "B20017_001E", "B01003_001E", "B02001_001E", "B02001_002E",
         "B01001_002E", "B01001_026E", "B01002_001E", "B01002_002E",
         "B01002_003E", "B20017_002E", "B20017_005E"),
region = "county:005,047,061,081,085",
regionin = "state:36",
key=myKey)

#update column names
names(bor_data)[which(names(bor_data)=="B20017_001E")] <- "Med_Income"
names(bor_data)[which(names(bor_data)=="B01003_001E")] <- "Population"
names(bor_data)[which(names(bor_data)=="B02001_001E")] <- "Race_Total"
names(bor_data)[which(names(bor_data)=="B02001_002E")] <- "White_Total"
names(bor_data)[which(names(bor_data)=="B01001_002E")] <- "Male_Total"
names(bor_data)[which(names(bor_data)=="B01001_026E")] <- "Fem_Total"
names(bor_data)[which(names(bor_data)=="B01002_001E")] <- "Median_Age"
names(bor_data)[which(names(bor_data)=="B01002_002E")] <- "Median_Age_Male"
names(bor_data)[which(names(bor_data)=="B01002_003E")] <- "Median_Age_Fem"
names(bor_data)[which(names(bor_data)=="B20017_002E")] <- "Median_Income_Male"
names(bor_data)[which(names(bor_data)=="B20017_005E")] <- "Median_Income_Fem"
```


```{r}
head(zcta_data)
```
   
   
```{r, message=FALSE}
#load additional viz libraries
library(rgdal)
library(viridis)
library(RColorBrewer)
```
   
```{r}
#read in the shape file for NYC zip codes
filepath <- "Shape_Files/ZIP_CODE_040114.shp"
NYC_zips <- readOGR(filepath, stringsAsFactors = F)

#get zip to borough
zip_bor <- read.csv("data/zip_borough.csv")

#get zipcodes from shape file
shpcodes <- NYC_zips@data$ZIPCODE %>% as.character %>% as.numeric

#now join these zip codes with the other data
dat <- data.frame(MODZCTA = shpcodes)
dat <- dplyr::left_join(dat, na.omit(cases), by="MODZCTA")
zcta_data$zip_code_tabulation_area <- as.numeric(zcta_data$zip_code_tabulation_area)
dat <- dplyr::left_join(dat, zcta_data, 
                        by = c("MODZCTA" = "zip_code_tabulation_area"))
dat <- dplyr::left_join(dat, zip_bor, by=c("MODZCTA" = "zip"))
dat$borough[which(dat$MODZCTA==10065)] <- "Manhattan"
dat$borough[which(dat$MODZCTA==10075)] <- "Manhattan"

case_bor <- dat %>% group_by(borough) %>% summarize(numcases = sum(Positive, na.rm=T), numtests = sum(Total, na.rm=T))
bor_data$Positive <- case_bor$numcases[c(4,2,3,5,1)]
bor_data$Tests <- case_bor$numtests[c(4,2,3,5,1)]
```
  
In case you want to write this to a new csv file that you can use!
```{r}
write.csv(bor_data, "data/coronavirus-nyc/data_summ_bor.csv", row.names = F)
write.csv(dat, "data/coronavirus-nyc/data_summ_zcta.csv", row.names = F)
```
  
```{r}
#calculate positive rate for tests
dat <- dat %>% 
  mutate(posrate =Positive/Population*100)

dat <- dat %>% mutate(Prop_White = White_Total/Race_Total,
                      Prop_NON_White = 1-(White_Total/Race_Total)) 
```
  
Now, we can replicate some of the maps:  
```{r}
#Function to get color information based on some data
getcolors <- function(data, ntile, missingcol, rdgrbl=c(1,0,0), mycolors=NULL){
  mybreaks <- c(-1, quantile(data, 
                             probs = seq(0, 1, length.out=ntile+1), 
                             na.rm = T))
  mycols <- rgb(rdgrbl[1],rdgrbl[2],rdgrbl[3], 
                seq(0.05,0.65, length.out = length(mybreaks)-1))
  if(!is.null(mycolors)){
    mycols <- mycolors
  }
  mycols[1] <- missingcol
  data[is.na(data)] <- -.1
  mycolorscheme <- cut(data, mybreaks) %>%
  as.numeric()
  mycolorscheme <- mycols[mycolorscheme]
  levs <- levels(cut(data, mybreaks))
  levs[1] <- "No Data"
  return(list(mycolorscheme, levs, mycols))
}

col_lev <- getcolors(round(dat$posrate*10,1), 5, "white", mycolors=viridis(6))

#plot
#note: looks better in a quartz window; to do this, need to type quartz() into console:
#then copy and paste code below into the console as well
plot(NYC_zips, col = col_lev[[1]], 
     main = "Positive Tests per 1000 People", cex = 10, lwd=0.01)
legend("topleft", 
       legend = col_lev[[2]], 
       fill = col_lev[[3]], cex = 0.8, title = "Pos Tests")
```
   
We could do the same type of plot by race if we were interested and then visually compare the maps:    
```{r}
col_lev <- getcolors(round(dat$Prop_NON_White*100,1), 5, "white", mycolors=viridis(6))

plot(NYC_zips, col = col_lev[[1]], 
     main = "Percent of Population that is Non-White", cex = 10, lwd=0.01)
legend("topleft", 
       legend = col_lev[[2]], 
       fill = col_lev[[3]], cex = 0.8, title = "% Non-White")
```

```{r}
col_lev1 <- getcolors(round(dat$Prop_NON_White*100,1), 5, "white", c(1,0,0))
col_lev2 <- getcolors(round(dat$posrate*10,1), 5, "white", c(0,0,1))

par(mfrow=c(1,3))
plot(NYC_zips, col = col_lev1[[1]], main = "nonwhite", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev2[[1]], main = "covid", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev1[[1]], main = "nonwhite+covid", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev2[[1]], add=T, cex = 10, lwd=0.05)

```
    
```{r}
plot(round(dat$Prop_NON_White*100,1),round(dat$posrate*10,1), xlab="percent non-white", ylab="pos cases per 1000 ppl", col=col_lev1[[1]], pch=16)
points(round(dat$Prop_NON_White*100,1),round(dat$posrate*10,1),col=col_lev2[[1]], pch=16)
#abline(lm(round(dat$posrate*10,1)~round(dat$Prop_NON_White*100,1)), lwd=2)
```


```{r}

tmp <- read.csv("data/data_summ_zcta.csv")
zcta_race_proportion$zipcode <- as.numeric(as.character(zcta_race_proportion$zipcode))
zcta_coll_hh$zipcode <- as.numeric(zcta_coll_hh$zipcode)
tmp2 <- dplyr::left_join(tmp, zcta_race_proportion, 
                        by = c("MODZCTA" = "zipcode"))
tmp2 <- dplyr::left_join(tmp2, zcta_coll_hh, 
                        by = c("MODZCTA" = "zipcode"))
tmp2 <- tmp2[,-5]

#write.csv(tmp2, "data/coronavirus-nyc/zipcode_vars.csv")

zipdata <- read.csv("data/coronavirus-nyc/zipcode_vars.csv")
```


```{r}

plot_title <- "College Share by Zipcode"
legend_title <- "College"
variableToPlot <-   zipdata$Bach_plus_prop

## you don't need to modify any of this code, but you may if you'd like    
source("getShapeColors.R") # need this function

col_lev <- getShapeColors(variableToPlot, nbreaks = 5, missingcol = "white", c(0,0,1))

# col_lev <- getcolors(variableToPlot, ntile=c(-1,0,20,40,60,80,100))
plot(NYC_zips, col = col_lev[[1]], 
     main = plot_title, cex = 10, lwd=0.05)
legend("topleft", 
       legend = col_lev[[2]], 
       fill = col_lev[[3]], cex = 0.8, title = legend_title)

# col_lev <- getcolors(variableToPlot, 5, "white", c(0,0,1))
col_lev <- getcolors(variableToPlot, nbreaks=c(0,20,40,60,80,100))
plot(NYC_zips, col = col_lev[[1]], 
     main = plot_title, cex = 10, lwd=0.05)
legend("topleft", 
       legend = col_lev[[2]], 
       fill = col_lev[[3]], cex = 0.8, title = legend_title)


# col_lev <- getcolors(variableToPlot, 5, "white", c(0,0,1))
col_lev <- getcolors(variableToPlot, missingcol = "white", nbreaks=10)
plot(NYC_zips, col = col_lev[[1]], 
     main = plot_title, cex = 10, lwd=0.05)
legend("topleft", 
       legend = col_lev[[2]], 
       fill = col_lev[[3]], cex = 0.8, title = legend_title)

```


#### Combining variables

```{r}
col_lev1 <- getcolors(round(dat$Prop_NON_White*100,1), 5, "white", c(1,0,0))
col_lev2 <- getcolors(round(dat$posrate*10,1), 5, "white", c(0,0,1))

par(mfrow=c(1,3))
plot(NYC_zips, col = col_lev1[[1]], main = "nonwhite", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev2[[1]], main = "covid", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev1[[1]], main = "nonwhite+covid", cex = 10, lwd=0.05)
plot(NYC_zips, col = col_lev2[[1]], add=T, cex = 10, lwd=0.05)

```








```{r}
# makeVarlist(name = "acs/acs5",
#             vintage = 2018,
#             find = "2-person household",
#             varsearch = "label")
                      
```
